# Header
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags
  Links: /links/index.html
  About: /curriculumvitae/index.html
  #Promises: /promises/index.html

# Google Analytics

google_analytics: UA-87274131-1

# Miscellaneous
favicon: https://s18.postimg.org/k7qcci1t5/s_icon.png
twitter: lazzzis
github: lazzzis
instagram: lazzzis
fb_app_id:
music: 30744948

# due to some reason, this has to be a url rather than id
google_plus: https://plus.google.com/114550357749490779368

# disable some share applications.
# For the details of all the applications, please refer to https://github.com/overtrue/share.js
share_disabled: weibo,qzone,qq,tencent,douban,linkedin,diandian
